print('Array fo Character')
print('hello '"world")
print('hello ',"world")
message = 'Hello World'
print('message[0:7]',message[0:7])
print('message[:7]',message[:7])
print('message[:-7]',message[:-7])
print('len(message)',len(message))
print('message[7:len(message)]',message[7:len(message)])
print('message.split("")',message.split(" "))
x,y,z=10,20,30
print('x,y,z=10,20,30')
print('- python의 string은 모두 array이다')
print('- array는 index를 갖는다.')
print('- index는 0부터 시작한다.')
print('message=',message)
print('message의 array에서 0부터 7까지 message[0:7] =',message[0:7])
print('message[:7]은 0이 생략되어 있다 ', message[:7])
print('message[:-7]은 뒤에서 부터 까지 ',message[:-7])
print('len(message) 문자 수를 구함', len(message),'글자')
print('message[3:len(message)]는 3부터 끝까지=',message[3:len(message)])
message = 'abc efg qqq'
print('message =',message)
print(message.split(" "))
x,y=10,20
print('x,y =',x,',',y)
print('x =',x)
print('y =',y)
x,y,z=message.split(' ')
print("x,y,z=message.split(' ')")
print('message =',message)
print('x,y,z =',x,',',y,',',z)
print(x+y)
print(x+' '+y)
print(x<y)
s1='bcd'
s2='absdfdsfds'
print('첫 글자의 아스키 코드로 처리됨 ',s1>s2)
print("한글">"가나다")
print("당신의 이름은 {}입니다".format('홍길동'))
print('Num is {:d}'.format(23))
print('Num is {:05d}'.format(23))